apiVersion: v1
kind: Service
metadata:
  namespace: dwk
  name: postgres-svc
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: postgres
  clusterIP: None
  selector:
    app: postgresapp
