apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dwk
  name: ping-pong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: sathirak/ping-pong:11
          ports:
            - containerPort: 3000