apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: log-output-writer
          image: sathirak/log-output-writer:2
          command: ["/app/main"] 
          volumeMounts:
            - name: shared-image
              mountPath: /usr/src/app/files
        - name: log-output-reader
          image: sathirak/log-output-reader:4
          command: ["/app/main"] 
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: shared-image
              mountPath: /usr/src/app/files
            - name: shared-data
              mountPath: /usr/src/app/shared
      volumes:
        - name: shared-image
          emptyDir: {}
        - name: shared-data
          persistentVolumeClaim:
            claimName: shared-claim