apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dwk
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: log-output-writer
          image: sathirak/log-output-writer:13
          command: ["/app/main"]
          volumeMounts:
            - name: config-volume
              mountPath: /usr/src/app/files
          envFrom:
            - secretRef:
                name: log-output-secret
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"

        - name: log-output-reader
          image: sathirak/log-output-reader:13
          command: ["/app/main"]
          volumeMounts:
            - name: config-volume
              mountPath: /usr/src/app/files
          envFrom:
            - secretRef:
                name: log-output-secret
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"