apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-claim # name of the volume claim, this will be used in the deployment
spec:
  storageClassName: manual # Changed from 'my-example-pv' to 'manual' to match PV
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi