apiVersion: v1
kind: Service
metadata:
  namespace: dwk
  name: ping-pong-svc
spec:
  type: LoadBalancer
  selector:
    app: ping-pong 
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3000