apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: dwk-project
  name: wiki-reader
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: wiki-reader
            image: sathirak/job:1
          restartPolicy: OnFailure
