apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: sathirak/ping-pong:4
          volumeMounts:
            - name: shared-data
              mountPath: /usr/src/app/shared
          ports:
            - containerPort: 3000
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: shared-claim